# Activity Monitor Configuration
# Monitors Claude Code hook activity with functional approach

[monitoring]
enabled = true
capture_tool_usage = true
capture_user_prompts = true
excluded_tools = []
hook_types = []  # Empty means monitor all hook types

[storage]
database_path = ".claude/activity_metrics.db" 
backup_enabled = false
cleanup_days = 30

[analytics]  
enable_insights = true
daily_summaries = true
performance_tracking = true

# Custom activity filters
[[filters]]
name = "large_operations"
condition = "content_size > 50000"
description = "Track operations with large content"

[[filters]]
name = "slow_commands" 
condition = "execution_time > 5000"
description = "Track slow executing commands"

[[filters]]
name = "file_operations"
condition = "tool_identifier == 'Edit'"
description = "Track file editing activities"

[[filters]]
name = "bash_activities"
condition = "tool_identifier == 'Bash'" 
description = "Track bash command usage"

[[filters]]
name = "prompt_interactions"
condition = "hook_category == 'UserPromptSubmit'"
description = "Track user prompt submissions"