---
name: Lint Code Base

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v8.0.0
        env:
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          VALIDATE_BASH: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true

          FILTER_REGEX_INCLUDE: '.*\.sh$|.*\.json$|.*\.md$|.*\.yml$|.*\.yaml$'
          FILTER_REGEX_EXCLUDE: 'CLAUDE\.md'

          BASH_CONFIG_FILE: .github/linters/.shellcheckrc

          BASH_SEVERITY: warning

          LOG_LEVEL: NOTICE
          DISABLE_ERRORS: false
